/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: e7xDWCHrckDsHY4UCLrxF3

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsodf4WzNv8F0O } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: ODF4WzNV8F0o/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsodf4WzNv8F0O
});
